vaadin-input.html
fixes #9 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-input/11)
=> Set autofocus programatically. Fix #9

test/performance/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-input/23)
=> Remove import polymer.html from performance tests

bower.json, demo/material-vaadin-input.html
Fixes #35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-input/37)
=> Fix transitions for Safari

test/control-state.html, test/index.html, test/text-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/44)
=> Move specific text field tests out of control state.

demo/index.html, test/validate.html, vaadin-text-field.html
Closes #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/49)
=> Prevent invalid input feature

demo/.eslintrc.json, demo/common.html, demo/validators.html
Connected to #28
I will add tests after discussing the implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/50)
=> Custom Validators

bower.json, vaadin-text-field.html
Closes #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/55)
=> Include vaadin-themable-mixin

gulpfile.js, test/.eslintrc.json, test/visual/default.html
Related to https://github.com/vaadin/vaadin-element-skeleton/pull/29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/58)
=> Fix linter config and linter errors

documentation.json, index.html, vaadin-control-state-mixin.html, vaadin-form-element-mixin.html, vaadin-text-field.html
Connects to https://github.com/vaadin/components-team-tasks/issues/239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/61)
=> Fix API docs

test/visual/test.js
The same issue as it was in form-layout: https://github.com/vaadin/vaadin-form-layout/blob/master/test/visual/test.js#L18-L23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/72)
=> Fix Firefox gemini tests

demo/styling.html, vaadin-text-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/77)
=> Update styling demo

demo/index.html, documentation.json, vaadin-text-field.html
This is the suggestion by one of DX testing participants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/78)
=> Add the pattern property description to the demo

test/text-field.html, vaadin-text-field.html
Fixes #40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/75)
=> Fix default value to be empty string

demo/index.html, documentation.json
Fixes #83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/87)
=> Remove autofocus demo

test/index.html, test/validation.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/88)
=> Add test covering the return value of validate() method

demo/index.html
Closes #85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/90)
=> Add a clarifying note about the error message

test/text-field.html, vaadin-text-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/91)
=> Remove name binding

vaadin-form-element-mixin.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/93)
=> superClass name makes more sense for the extended class

vaadin-text-field.html
fixes #103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/104)
=> Fixing margins and id of the error message

vaadin-password-field.html
It is not used in this element.
=> Remove Polymer.GestureEventListeners

test/password-field.html, vaadin-password-field.html
Fixes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/121)
=> Mask the password on blur

test/text-field.html, vaadin-text-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/119)
=> Fix hasValue attribute when value is null or undefined. Fixes #118

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/127)
=> Add gemini tests in IE build step

README.md
Updated demo link to include password-field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/132)
=> Updated demo link.

demo/password.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/133)
=> Demonstrate label property for the password-field

demo/validators.html
Connected to vaadin/components-team-tasks#280
Fixes https://gitlab.vaadin.com/vaadincom/webpage/issues/1760
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/144)
=> Use HTTPS protocol for AJAX request

test/password-field.html, vaadin-password-field.html
Fixes #147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/151)
=> Prevent mousedown event on reveal-button

vaadin-text-area.html
Connects to https://github.com/vaadin/vaadin-core/issues/101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/155)
=> Simplified the prototype

analysis.json, src/vaadin-password-field.html, src/vaadin-text-area.html, src/vaadin-text-field-mixin.html, src/vaadin-text-field.html, test/text-field.html, theme/lumo/vaadin-text-field.html
Fixes #186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/194)
=> Add has-label attribute for styling

src/vaadin-password-field.html, test/password-field.html
Fixes #218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/219)
=> Make sure change gets called on blur

.travis.yml, src/vaadin-text-field-mixin.html, test/accessibility.html, test/password-field.html, test/text-area.html, test/text-field.html, test/validation.html, wct.conf.js
Connected to vaadin/components-team-tasks#332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/217)
=> Use bare module specifiers in the P3 conversion

analysis.json, src/vaadin-text-area.html, src/vaadin-text-field.html
Fixes #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/227)
=> Suffix & prefix docs

bower.json, theme/material/vaadin-password-field-styles.html, theme/material/vaadin-password-field.html, theme/material/vaadin-text-area-styles.html, theme/material/vaadin-text-area.html, theme/material/vaadin-text-field-styles.html, theme/material/vaadin-text-field.html
Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/232)
=> Adding theme/material

src/vaadin-text-area.html, test/text-area.html
Fixes #267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/271)
=> Dispatch `iron-resize` event on text-area height change

demo/text-field-validators-demos.html
Fixes #265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/276)
=> Fix demos: check if custom element already defined [skip ci]

src/vaadin-text-field-mixin.html, test/text-field.html
Fixes #279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/280)
=> Fix change event

src/vaadin-password-field.html, test/password-field.html
Fixes #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/286)
=> Use focusout instead of blur for cached change event dispatching

src/vaadin-text-field-mixin.html, test/text-field.html
Add `autoselect` – automatically select content when focused #288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/294)
=> Add autoselect

README.md, bower.json, demo/demos.json, demo/email-field-demos.html, demo/index.html, src/vaadin-email-field.html, test/email-field.html, test/test-suites.js, theme/lumo/vaadin-email-field.html, theme/material/vaadin-email-field.html, vaadin-directory-description.md, vaadin-email-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/290)
=> Add <vaadin-email-field> component

src/vaadin-text-field-mixin.html, test/text-field.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/300)
=> fix: ensure slotchange input listeners removal does not throw

src/vaadin-number-field.html, test/number-field.html
Fixes #306 
Visual tests are failing for an unrelated issue 🤷‍♂️
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/307)
=> Fix value control behaviour when value is out of range

src/vaadin-text-field-mixin.html, test/text-field.html
Fixes #312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/313)
=> Clear the native input value when setting to undefined

src/vaadin-email-field.html, src/vaadin-number-field.html
Add correct version to `vaadin-email-field`and `vaadin-number-field`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/314)
=> Update element version numbers

src/vaadin-text-field-mixin.html
Fixes [vaadin/vaadin-text-field/issues/321](https://github.com/vaadin/vaadin-text-field/issues/321)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/322)
=> Add _onBlur method to be registered with the blur event

src/vaadin-text-field-mixin.html, test/text-field.html
Fixes #328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/329)
=> Remove preventInput flag on requestAnimationFrame

src/vaadin-text-field-mixin.html, test/text-area.html, test/text-field.html
Fixes #323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/338)
=> Fix host attribute propagation

src/vaadin-number-field.html, test/number-field.html
Connected to https://github.com/vaadin/vaadin-text-field/issues/339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/343)
=> Refactor and fix step calculation

src/vaadin-text-area.html, src/vaadin-text-field-mixin.html, src/vaadin-text-field.html, test/accessibility.html
Fixes #348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/354)
=> feat: add i18n API for clear button accessible label

src/vaadin-text-field-mixin.html, test/text-field.html
Fixes #352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/355)
=> feat: prevent default on clear button click

src/vaadin-text-field-mixin.html, test/text-field.html, wct.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/371)
=> Remove _valueClearing on mouseleave

src/vaadin-text-field-mixin.html, test/accessibility.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/382)
=> Dispatch change on ESC clearing the value

demo/demos.json, demo/email-field-demos.html, demo/password-field-demos.html, demo/text-area-demos.html, demo/text-field-basic-demos.html, demo/text-field-form-demos.html, demo/text-field-prefix-suffix-demos.html, demo/text-field-styling-demos.html, demo/text-field-theme-demos.html, demo/text-field-validators-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/386)
=> Fix text-field demos

demo/number-field-demos.html, demo/text-field-validators-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/387)
=> Updating demos

src/vaadin-text-area.html, src/vaadin-text-field-mixin.html, src/vaadin-text-field.html, test/accessibility.html
Connected to vaadin/vaadin-select#191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/392)
=> fix(a11y): improve for <vaadin-select> use case

src/vaadin-number-field.html, test/number-field.html
Connected to https://github.com/vaadin/vaadin-text-field-flow/issues/172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/381)
=> Don't adjust decimal places based on step, fix decimal calc

wct.conf.js
Make Saucelabs tests pass again
=> chore(wct): Update wct config

test/.eslintrc.json, test/custom-input.html, test/helpers.html, test/text-area.html, test/text-field.html
=> test: fix flaky tests

src/vaadin-text-field-mixin.html, test/accessibility.html, test/email-field.html, test/number-field.html, test/text-area.html, test/text-field.html, test/validation.html
=> fix: stuck in invalid state after last validation constraint is removed while invalid

src/vaadin-number-field.html
=> fix(number-field): reset pointer-events properly [skip ci]

src/vaadin-number-field.html, test/number-field.html
=> fix(number-field): prevent readonly value change with keys

src/vaadin-number-field.html, test/number-field.html
Connected to https://github.com/vaadin/vaadin-text-field-flow/pull/261
=> Override validate to change invalid state instead of checkValidity

bower.json, src/vaadin-text-field-mixin.html, test/validation.html
* Add __forceCheckValidity and test
* chore: add explicit sinonjs dependency
* Add note
* Update screenshots
=> Add __forceCheckValidity (#452)

src/vaadin-email-field.html, theme/lumo/vaadin-email-field-styles.html, theme/lumo/vaadin-email-field.html
=> fix: make email field work like in LTR on RTL mode

src/vaadin-text-field-mixin.html, test/text-field.html
=> Fix user input (#480)

src/vaadin-text-field-mixin.html, test/integer-field.html
See https://github.com/Polymer/polymer/issues/5259
=> fix: workaround Polymer getProperty with mixins/observers (#484)

src/vaadin-email-field.html, test/email-field.html
Fixes https://github.com/vaadin/vaadin-text-field/issues/499
=> fix: don't override custom pattern

src/vaadin-email-field.html, test/email-field.html, test/text-area.html, test/text-field.html
=> Fix autocapitalize tests in Firefox, improve email pattern

src/vaadin-email-field.d.ts, src/vaadin-email-field.js, src/vaadin-integer-field.d.ts, src/vaadin-integer-field.js, src/vaadin-number-field.d.ts, src/vaadin-number-field.js, src/vaadin-password-field.d.ts, src/vaadin-password-field.js, src/vaadin-text-area.d.ts, src/vaadin-text-area.js, src/vaadin-text-field.d.ts, src/vaadin-text-field.js
1. Added events descriptions to `@fires` annotations
2. Removed event types as they are not picked up by TS.
=> chore: update JSDoc for custom events [skip ci]

src/vaadin-text-field-mixin.js, test/text-field.test.js
Fixes https://github.com/vaadin/vaadin-date-picker/issues/788
=> fix: iron-resize event is now composed

src/vaadin-text-area.html, test/text-area.html
cherry-pick of https://github.com/vaadin/web-components/pull/2784
Part of: https://github.com/vaadin/flow-components/issues/2077
=> feat: add text area pattern validation (CP: 14.8)

src/vaadin-text-field-mixin.html
This PR adds the JSDoc for the validated event that was added as a new feature 
- https://github.com/vaadin/vaadin-text-field/pull/614
=> docs: add JSDoc for validated event (CP: 14)

test/email-field-events.html, test/integer-field-events.html, test/number-field-events.html, test/password-field-events.html, test/text-area-events.html, test/text-field-events.html
Backports the following PRs:
- https://github.com/vaadin/web-components/pull/5609
=> test: ensure _hasInputValue is reset on clear button interaction (CP:14) 
