vaadin/vaadin-text-field

.travis.yml

Related to https://github.com/vaadin/vaadin-element-skeleton/pull/22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-input/18)

Separate `lint` and `perf:run` tasks, add travis_retry to `perf:run`

---

.eslintrc.json
package.json

We don't need the `arrow-spacing` rule after https://github.com/vaadin/eslint-config-vaadin/pull/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/57)

Cleanup eslint config

---

vaadin-text-field.html

Connected to https://github.com/vaadin/components-team-tasks/issues/251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/96)

Throw error when used with wrong Polymer version

---

vaadin-text-field.html

I made few changes to declare all properties using long form, and also a small cleanup of string literals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/97)

Use consistent properties declarations. Some cleanup

---

vaadin-text-field.html

Partly revert https://github.com/vaadin/vaadin-text-field/pull/104 according to the CR conversation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/105)

Remove unrelated to default theme styles for error-message

---

test/.eslintrc.json
test/validation.html

Replacing `setTimeout` with `animationFrameFlush`.
Skipping 'call validate' test on IE11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/115)

Fix tests in IE11

---

vaadin-password-field.html

Fixed #112 
> When the password-field text is not visible => iPhone shows lowercase keyboard. When the password-field text is visible => iPhone shows uppercase keyboard (for the first letter). Inconsistent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/111)

Add autocapitalize="off" for password-field

---

vaadin-password-field.html

It's already extended in the `text-field`: https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/123)

Remove themable-mixin from password-field

---

analysis.json
demo/password.html
test/password-field.html
vaadin-password-field.html

This PR renames `hideToggleButton` to `revealButtonHidden`. 
- the `toggle` -> `reveal` part of renaming was requested by @Jouni https://github.com/vaadin/vaadin-text-field/pull/114#issuecomment-323037271
- the `hide*` to `*Hidden` part of renaming was suggested by @tomivirkki, the reason is in Flow-side there will be getters and setters, `getRevealButtonHidden()` is much in readability then `getHideRevealButton()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/122)

API rename: hideToggleButton -> revealButtonHidden

---

test/text-field.html

After merging https://github.com/vaadin/vaadin-control-state-mixin/pull/17 small change is needed for label-click test
Current master is broken: https://travis-ci.org/vaadin/vaadin-text-field/builds/272056097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/135)

Fix label click test

---

demo/index.html
test/accessibility.html
test/password-field.html
test/text-field.html
test/validation.html
vaadin-password-field.html
vaadin-text-field.html

Connected to https://github.com/vaadin/components-team-tasks/issues/280
Fixes https://gitlab.vaadin.com/vaadincom/webpage/issues/1764
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/142)

Prefix classes, remove id='input' to avoid collisions

---

test/text-field.html

Remove test as this functionality is already tested in control-state-mixin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/143)

Remove focus test

---

vaadin-password-field.html

Having the icon styles in the core styles makes it more difficult to override them in a new theme, as the core styles come after the theme in the source order, so the theme needs to use more specific selectors to override them.
Also, these are purely aesthetic aspects of the component, so they should be in the theme.
It is still very easy for a developer to get those styles in their own theme if needed, by including the default theme in their own theme:
```html
<dom-module id="valo-password-field" theme-for="vaadin-password-field">
<template>
<style include="vaadin-password-field-default-theme">
…
</style>
</template>
</dom-module>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Move reveal button icon styles from core styles to the default theme

---

vaadin-text-field-mixin.html

Fixes https://github.com/vaadin/vaadin-date-picker/issues/424
Add `reflectToAttribute` key to `required` property
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/159)

Make required property reflect to attribute

---

analysis.json
vaadin-text-area.html
vaadin-text-field-mixin.html
vaadin-text-field.html
wct.conf.js

Fixes https://github.com/vaadin/vaadin-combo-box/issues/548
Fixes https://github.com/vaadin/vaadin-date-picker/issues/444
Add `reflectToAttribute` key to `readonly` property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/158)

Make readonly property reflect to attribute

---

test/password-field.html
vaadin-password-field.html

Fixes #116
There was a regression in v1.1.0 that caused the field not getting focused on password reveal (if not focused beforehand). The issue is described in [this comment](https://github.com/vaadin/vaadin-text-field/issues/116#issuecomment-346966907)
This PR fixes the regression
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/174)

Make sure the field has focus when revealed

---

theme/valo/vaadin-text-area.html
theme/valo/vaadin-text-field.html

The order in which matching style modules are included in an element template is not consistent.
So the current approach makes the theme look broken in case text field styles get included _after_ text area specific styles (that are supposed to override text-field styles) in the text area template.
Need to add an explicit include for text field valo styles prior to text-area specific styles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/176)

Ensure text area styles override text field styles in text area

---

src/vaadin-text-field-mixin.html

Enable the slotted part=“value” to flex (fixes vaadin-dropdown-menu
styles).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/180)

Fix CSS specificity

---

src/vaadin-text-field-mixin.html
src/vaadin-text-field.html
theme/valo/vaadin-password-field.html
theme/valo/vaadin-text-area.html

This solution works better than the previous one, as the developer can now control the min-width with the host element, and the prefix/suffix elements won’t grow the field width on top of that (they “eat into” the host width).
Add a new CSS custom property for setting the default width.
Remove unnecessary style module include from password-field (duplicate include).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/181)

Make text-field min-width work like native input

---

bower.json
demo/demos.json
demo/index.html
demo/text-area-demos.html
demo/text-field-basic-demos.html
demo/text-field-form-demos.html
demo/text-field-password-demos.html
demo/text-field-prefix-suffix-demos.html
demo/text-field-rtl-demos.html
demo/text-field-styling-demos.html
demo/text-field-validators-demos.html
demo/text-field-valo-theme-demos.html
src/vaadin-password-field.html
test/visual/vaadin-password-field/valo.html
test/visual/vaadin-text-area/valo.html
test/visual/vaadin-text-field/valo.html
theme/valo/vaadin-password-field.html
theme/valo/vaadin-text-area.html
theme/valo/vaadin-text-field.html

- Remove tabindex example (not a best practice)
- Remove data binding example (Polymer specific, not a text field
feature)
- Hide iron-form example (couldn’t get it to work). Can be added back
later if the binding scope is working
- Extract prefix and suffix examples (including icons) and RTL example
to separate pages
- Add a styling examples, which includes probably the most common
customizations (input field border and background)
- Extract all validation related examples into a separate page
- Remove “contrast” example from Valo theme examples
- Refactor text alignment to be a theme variation, not a CSS custom
property (allows other customizations that rely on this, such as the
mask image)
- Add a CSS custom property for hiding the password field reveal button
- Adjust the password …

Restructure demos (plus minor theme updates)

---

theme/valo/vaadin-text-field.html

Make read-only fields visually distinct from normal fields.
Show focus-ring also for read-only fields.
Make label color transition faster (was previously quite slow).
Set the disabled text color for prefix and suffix elements as well.
Fix an issue for vaadin-dropdown-menu-text-field, which would get the
secondary text color for the selected value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/183)

Updates to Valo theme

---

theme/valo/vaadin-text-field.html

The alignment could go off when the parent page is using a different font or line-height. Not setting the line-height to 1 fixes the issue (can be seen in the vaadin-date-picker “Using as a Form Field” demo).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/184)

Fix vertical align guide element positioning

---

theme/valo/vaadin-text-field.html

The activation effect was not visible on touch devices after the latest theme updates.
Adjust the strength of the effect a little at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/187)

Enable activation effect on touch devices

---

theme/valo/vaadin-text-area.html

Since the pseudo element doesn’t scroll with the input field, we’ll just use a background-color transition for the hover/active effect.
The text-field transition can actually look too distracting on large text areas, so this is probably even a better design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/188)

Fix text area activation effect

---

theme/valo/vaadin-text-field.html

Connected to vaadin/vaadin-valo-styles#45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/189)

Workaround mask-image CSS property to prevent crash in Edge

---

analysis.json
src/vaadin-text-area.html
src/vaadin-text-field-mixin.html
src/vaadin-text-field.html
test/text-field.html

Fixes #195 
Note: the whole JS code of the mixin used to have bad indentation, so I fixed it in the first commit. Please ignore it, only the second commit is relevant for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/197)

Dispatch change event on native element change

---

src/vaadin-text-field-mixin.html
src/vaadin-text-field.html
test/text-field.html

Connected to vaadin/vaadin-date-picker#517
The link to the original [IE bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/).
@platosha I know you don't like flags but this time I really have no idea how to handle it better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/203)

Workaround IE11 placeholder issues

---

src/vaadin-password-field.html
test/password-field.html

Fixes #193 
See [#193 (comment)](https://github.com/vaadin/vaadin-text-field/issues/193#issuecomment-373349557) for the behavior which this PR is expected to achieve.
Tested in Simulator (9.3 and 11.2) and with the real iPhone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/209)

Fix reveal-button scrolling behavior for iOS

---

.travis.yml
theme/lumo/vaadin-text-field-styles.html
wct.conf.js

Fixes scroll handle not visible when used inside of the grid (Mac OS Chrome)
The same has been already applied in
vaadin/vaadin-button#83
vaadin/vaadin-checkbox#83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/253)

Remove will-change property to prevent grid scroll issue

---

bower.json
demo/text-field-validators-demos.html

Connected to vaadin/components-team-tasks#389
Depends on vaadin/vaadin-demo-helpers#55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/259)

Ignore ES6 demos in IE11 properly [skip ci]

---

src/vaadin-text-field-mixin.html
test/text-field.html

Connects to #269 
Requires first this to be merged and released: https://github.com/vaadin/vaadin-control-state-mixin/pull/47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/270)

Don't throw an error when focusing a newly created text-field

---

src/vaadin-text-area.html
test/text-area.html

Fixes #254 
Implemented in `text-area`, not in the `element-mixin` as was discussed in person.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/278)

Animationend update height

---

demo/text-field-basic-demos.html
src/vaadin-text-field-mixin.html
test/text-field.html

The tests for autoselect are broken on master, as we forgot to merge into branch and run push build before merging. This workaround fixes the regression.
Confirmed the need for `setTimeout` in simulator, it doesn't select the text without it.
See also [stackoverflow thread](https://stackoverflow.com/questions/3272089/programmatically-selecting-text-in-an-input-field-on-ios-devices-mobile-safari#comment60319255_6302507) where I actually found this workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/295)

Fix autoselect tests on iOS 9, add missing demo

---

src/vaadin-text-field-mixin.html
test/text-field.html

Fixes https://github.com/vaadin/vaadin-ordered-layout/issues/68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/299)

Don't flex-grow the input-field part of a text-field

---

demo/demos.json
demo/number-field-demos.html
src/vaadin-number-field.html
test/number-field.html

Connects to https://github.com/vaadin/vaadin-text-field/issues/296
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/292)

Improve vaadin-number-field

---

src/vaadin-number-field.html
test/number-field.html

Fixes "With `<vaadin-number-field has-controls min="2"></vaadin-number-field>`, the + button will set the value to 1 first (same problem with max="-2")"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/303)

Fix setting min/max value with controls

---

theme/lumo/vaadin-password-field-styles.html

Fixes #315 
Can be tested using following snippet:
```
<vaadin-password-field>
<input type="password" slot="input">
</vaadin-password-field>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/316)

fix: workaround slotted password field -ms-reveal [skip ci]

---

src/vaadin-email-field.html
src/vaadin-number-field.html
src/vaadin-password-field.html
src/vaadin-text-area.html
src/vaadin-text-field-mixin.html
test/accessibility.html
test/custom-input.html
test/email-field.html
test/number-field.html
test/password-field.html
test/text-area.html
test/text-field.html
test/validation.html

Connects to https://github.com/vaadin/vaadin-select/issues/182
Required by https://github.com/vaadin/vaadin-select/pull/183
As in `vaadin-select` example `inputElement` and `focusElement` are not always the same, so new `inputElement` getter is introduced in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/317)

Introduce inputElement getter

---

src/vaadin-text-field-mixin.html

Fixes https://github.com/vaadin/vaadin-date-picker/issues/634
There was a minor timing issue with preventing `input` event occurring on `focusin` which leads to the problem with https://github.com/vaadin/vaadin-date-picker/issues/634 .
The solution is still covered with the tests, however the timing is difficult to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/326)

Simplify input event prevention

---

theme/material/vaadin-number-field-styles.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/327)

fix: replace lumo leftovers in number-field material

---

theme/material/vaadin-text-field-styles.html

Improve slotted selector for Firefox 47 which is used in visual tests.
This issue causing problems with visual tests in `datepicker` on master.
Related to https://github.com/vaadin/vaadin-date-picker/pull/637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/337)

Improve slotted selector for ff47

---

src/vaadin-number-field.html
test/number-field.html

- Allow programmatically setting any value regardless of step
- Change clicking + or - to increment or decrement value to the next multiple of step (offset by the min)
- Change checkValidity to check when value is not multiple of step (offset by the min)
- Change value to always return a string
Fixes #331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/333)

Fix number-field value and step issues

---

src/vaadin-text-field-mixin.html
test/text-field.html

Fixes #347
Fixes #233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/353)

feat: add input event support (test, doc, dispatch on clear)

---

src/vaadin-text-field-mixin.html
test/accessibility.html
test/text-field.html

Programmatically setting the value after clicking the clear button didn't work properly making the input look like empty but displaying the clear button and the component still had a value. This caused more easily noticeable issues with other components that internally use vaadin-text-field (when using the clear button).
Fixes #365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/366)

fix: clear button related bug

---

src/vaadin-number-field.html
test/number-field.html

Found a typo which has been unnoticed for a while 🙈 
Not sure if we actually need these to be reflected to attributes. Maybe we could just remove these lines, as it has never worked, and nobody has any complaint 🤔
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-text-field/384)

fix(number-field): reflect to attribute properly

---

src/vaadin-text-field-mixin.html
test/number-field.html

Fixes https://github.com/vaadin/flow/issues/6070
Fixing the issue with try -> catch feels a bit unclean. Another approach would be to check the type of the input, but then we'd need to include a list of arbitrary input types that do support `setSelectionRange`.

fix: Suppress error on autoselect workaround

---

src/vaadin-number-field.html
test/number-field.html

Fixes #395
Once merged, this should probably be backported to `2.3` branch together with 827b839.

Fix number-field step up/down buttons don't work with some values

---

src/vaadin-number-field.html
test/number-field.html

Setting a number value causes the component to convert it to string and
thus change the value another time.
fix #413

fix: duplicate value-changed events from number-field buttons

---

src/vaadin-text-field.html

based on https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title
fix #293

docs: fix title-property JSDoc [skip ci]

---

src/vaadin-integer-field.html
src/vaadin-text-field-mixin.html

Protected feature extracted from `<vaadin-integer-field>` to allow
reusing the same logic for `BigDecimalField`.

feat/refactor: add _enabledCharPattern property

---

src/vaadin-text-field-mixin.html
test/integer-field.html

By double-checking the `_enabledCharPattern` with the experimental
`beforeinput` event.
Fix #429

fix: prevent entering period to IntegerField on mobile

---

src/vaadin-number-field.html
test/integer-field.html
test/number-field.html

setting the min or max property should not trigger step-based validation
fix #420

fix: avoid using initial step in validation

---

theme/lumo/vaadin-text-field-styles.html

Fixes #335 
It turns out that the following CSS does not work and breaks the whole block:
```css
::slotted(input):focus
```
So I had to use `:host([focused])` instead to fix that.

fix(lumo): use correct focus state selector

---

.travis.yml
src/vaadin-text-field-mixin.html
test/accessibility.html

Do not set `aria-disabled`, `aria-required` or `aria-readonly` attributes since they are unnecessary when we're using the native HTML `disabled`, `required` and `readonly` attributes. Previously these three `aria-*` attributes were set with incorrect value (valid values for these are string `"true"` or `"false"`).
Use correct values for setting `aria-invalid` attribute (using string `"true"` when invalid).
Fixes #430.

fix: ARIA for disabled, required, readonly and invalid states

---

theme/lumo/vaadin-number-field-styles.html
theme/lumo/vaadin-text-field-styles.html

Connected to https://github.com/vaadin/vaadin-text-field-flow/issues/302

Don't use :not() selector for overflow-mask-image

---

src/vaadin-text-field-mixin.html
test/accessibility.html
test/text-field.html

A 3rd custom element using `vaadin-text-field` and defining a slot area for the `vaadin-text-field`'s helper slot was making `vaadin-text-field` see the slot element as a slotted contend and setting `has-helper="slotted"` to itself.
This change uses flattened nodes to check the presence of slotted elements on `vaadin-text-field` `helper` slot.
In this change
- use `FlattenedNodesObserver` instead of `slotchange` event
- use `FlattenedNodesObserver.getFlattenedNodes` to get slot children
- apply changes to tests
- remove checks for unsupported types

fix: use flattened nodes on helper slot

---

src/vaadin-text-field-mixin.html
test/text-field.html

Fixes https://github.com/vaadin/vaadin-text-field-flow/issues/273
**Description:**
`paste` is also triggering `input` event.
In case this event is triggered when value wasn't changed (i.e. value was replaced with `paste`, or `maxlength` is set and `paste` is done), `__userInput` will be set to `true` [here](https://github.com/vaadin/vaadin-text-field/blob/bd388d6bab1a08ae9fb5f68e95d513004c9592cb/src/vaadin-text-field-mixin.html#L428), but [updating the value](https://github.com/vaadin/vaadin-text-field/blob/bd388d6bab1a08ae9fb5f68e95d513004c9592cb/src/vaadin-text-field-mixin.html#L430) won't pass polymer dirty check, so the `__userInput` will be preserved for the next programmatic value update and input `value` won't be [updated](https://github.com/vaadin/vaadin-text-field/blob/bd388d6bab1 …

Fix user input

---

src/vaadin-text-field-mixin.html
test/integer-field.html

See https://github.com/Polymer/polymer/issues/5259
Fixes https://github.com/vaadin/vaadin-text-field-flow/issues/317

fix: workaround Polymer getProperty with mixins/observers

---

src/vaadin-text-field-mixin.html
test/integer-field.html

See https://github.com/Polymer/polymer/issues/5259

fix: workaround Polymer getProperty with mixins/observers (#484)

---

src/vaadin-number-field.html
src/vaadin-password-field.html
src/vaadin-text-field-mixin.html

Connected to https://github.com/vaadin/vaadin-core/issues/257
Note, this is a PR for 2.7 branch. When cherry-picking it to master, we would need to add attribute for `helperText`.

docs: add JSDoc for attributes [skip ci]

---

src/vaadin-number-field.html
src/vaadin-password-field.html
src/vaadin-text-field-mixin.html

docs: add JSDoc for attributes [skip ci] (#489)

---

src/vaadin-email-field.d.ts
src/vaadin-email-field.js
src/vaadin-integer-field.d.ts
src/vaadin-integer-field.js
src/vaadin-number-field.d.ts
src/vaadin-number-field.js
src/vaadin-password-field.d.ts
src/vaadin-password-field.js
src/vaadin-text-area.d.ts
src/vaadin-text-area.js
src/vaadin-text-field.d.ts
src/vaadin-text-field.js

Added missing `change` and `input` events to align with the [API docs](https://cdn.vaadin.com/vaadin-text-field/3.0.0-alpha1/#/elements/vaadin-text-field#events).
There is also `iron-resize` event but it's mostly internal and was implemented mainly for `vaadin-grid` editor (#372)
So I don't think we should encourage using it, assuming that we will move away from Polymer in future.

chore: align JSDoc, add missing events [skip ci]

---

src/vaadin-text-area.js

Fixes https://github.com/vaadin/vaadin-flow-components/issues/452
Seems that the original issue happens because of [this workaround](https://github.com/vaadin/vaadin-text-field/blob/154933d877f6bff2520397b79cc26788629c8101/src/vaadin-text-area.js#L197). According to the comment above the line, the workaround could be scoped to target Safari only, but since I couldn't reproduce the "jumpy Safari rendering" mentioned in the comment anymore (the workaround is from 2017), decided to just remove it.
This PR doesn't have an associated test case, because it would require using native focus.

fix: remove an outdated workaround for Safari

---

src/vaadin-text-area.html

Cherry-pick https://github.com/vaadin/vaadin-text-field/pull/568

fix: scope a Safari-specific workaround

---

src/vaadin-text-area.html
src/vaadin-text-field.html
test/text-area.html
test/text-field.html

cherry pick of https://github.com/vaadin/web-components/pull/2232 for v14
cherry pick of https://github.com/vaadin/web-components/pull/2251 for v14
cherry pick of https://github.com/vaadin/web-components/pull/2256 for v14
chore: move helper tests with own fixture into own suite

fix: do not focus the field on helper element click

---

src/vaadin-text-area.html

This change prevents the page from scrolling while the text area is measuring its height as part of the auto resize feature.
The solution involves temporarily fixing the height of the `textarea` container element, while the height of the `textarea` element is set to `auto` for measuring purposes. By setting a fixed height on the container we can ensure that the page height does not change during measurement, which prevents the browser from automatically adjusting the scroll position of the page.
Fixes https://github.com/vaadin/web-components/issues/291
Merging this would make #578 obsolete.

fix: prevent page scroll when resizing text area

---

src/vaadin-text-area.html

Backport https://github.com/vaadin/web-components/pull/2981 for V14

fix: workaround disabled textarea freezing Firefox (#2981)

---

src/vaadin-text-area.html
test/text-area.html

Backport https://github.com/vaadin/web-components/pull/3495 to V14

fix: don't cancel text-area wheel event unnecessarily (CP)

---

src/vaadin-text-field-mixin.html
test/email-field-validation.html
test/integer-field-validation.html
test/number-field-validation.html
test/password-field-validation.html
test/text-area-validation.html
test/text-field-validation.html

Backports the following PRs as part of an EoD task:
- https://github.com/vaadin/web-components/pull/4084

feat: fire a validated event on validation (CP: 14)

---

src/vaadin-text-field-mixin.html
test/email-field-validation.html
test/integer-field-validation.html
test/number-field-validation.html
test/password-field-validation.html
test/text-area-validation.html
test/text-field-validation.html

Reverted https://github.com/vaadin/vaadin-text-field/pull/613. It was decided not to backport the PRs preventing initial validation as it is a breaking change.

revert: "fix: prevent initial validation when the field is initialized as invalid"

---

src/vaadin-number-field.html
src/vaadin-text-area.html
src/vaadin-text-field-mixin.html

Backports the following PRs:
- https://github.com/vaadin/web-components/pull/5586

refactor: input value getters and setters (CP: 14)

---

src/vaadin-text-field-mixin.html
test/email-field-events.html
test/integer-field-events.html
test/number-field-events.html
test/password-field-events.html
test/text-area-events.html
test/text-field-events.html

Backports the following PRs:
- https://github.com/vaadin/web-components/pull/5599

fix: reset _hasInputValue on programmatic value clear (CP: 14)
